version: '3.9'

networks:
  alakazam:
    external: true

services:

  reverse-proxy:
    image: nginx    
    depends_on:
        - demo-api-2
        - demo-api-3
    volumes:
    - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    restart: always
    
    
  demo-api-2:
    build: C:/Users/mlmsa/source/repos/DemoAPI2
    ports:
    - 8081:80
    
  demo-api-3:
    build: C:/Users/mlmsa/source/repos/DemoAPI2
    ports:
    - 8082:80
    

    
    