version: '3.9'

networks:
  alakazam:
    external: true

services:

  reverse-proxy:
    image: nginx    
    depends_on:
        - customer-order-system-aspnet
    volumes:
    - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    restart: always
        
  customer-order-system-aspnet:
    build: C:/Users/mlmsa/Desktop/EaterySystem/customer-order-system-aspnet
  
  db:
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: "order_system"
        MYSQL_ROOT_PASSWORD: "root"        
    ports:
    - "3307:3306"

    
    